# Generated by Django 5.0.3 on 2024-03-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='face_detected_model',
        ),
    ]
